[tool.poetry]
name = "logger"
version = "0.1.0"
description = ""
authors = ["Flavio Wu <flaviowu@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
